owner: oronder # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Oronder
    url: $ORONDER_HEARTBEAT_API

status-website:
  name: Oronder
  cname: uptime.oronder.com
  favicon: https://www.oronder.com/favicon.ico
  faviconSvg: https://www.oronder.com/favicon-32x32.png
  logoUrl: https://avatars.githubusercontent.com/u/143735829?s=200&v=4
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Discord
      href: https://discord.gg/Adg48Xrs6K
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
